name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rustc and clippy nightly
      uses: actions-rs/toolchain@v1
      with:
         profile: minimal
         toolchain: nightly
         override: true
         components: cargo, rustc, clippy
    - name: Basic tests (Async)
      run: make async-tests
    - name: Basic tests (Sync)
      run: make sync-tests
    #Do liniting last because it is most likely to fail
    - name: Linting (Async)
      run: make async-lint
    - name: Linting (Sync)
      run: make sync-lint
